spring:
  datasource:
    url: jdbc:mysql://localhost:3306?organize_oa
    username: root
    password: Zrx@20041009
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password: Zrx@20041009
  mail:
    default-encoding: UTF-8
    host: smtp.qiye.aliyun.com
    username: wxxydeveloper@x-lf.cn
    password: 114477225588Zcw
    properties:
      form: wxxydeveloper@x-lf.cn
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: TRACE
    sun.rmi: OFF
    org.apache.tomcat: WARN
server:
  port: 8155