server:
  port: 8155
  max-http-header-size: 10240
spring:
  datasource:
    url: jdbc:mysql://localhost:3306?organize_oa
    username: root
    password: Zrx@20041009
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
  profiles:
    active: test
  mail:
    host: 171.38.91.172
    username: zrx
    password: Zrx@20041009
mybatis:
  configuration:
    map-underscore-to-camel-case: true




