server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: organize_oa
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: local
    port: 6379
    password:
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true