spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true

